Use test;

DROP TABLE IF EXISTS book;


CREATE TABLE test.book (
	  id int(11)NOT NULL auto_increment,
	  title varchar(100) not null,
    description varchar(255) not null,
    author varchar(100) not null,
    isbn varchar(20) not null,
    printYear int(11) not null,
    readAlready bit(1) not null,
    primary key(id)
)
engine InnoDB,
collate = 'utf8_general_ci';

insert into book (id, title, description, author, isbn, printYear, readAlready) values (0, 'Carrie','Hailed as a modern classic, the brilliant, unforgettable debut Novel that started it all, "Carrie" introduced a distinctive new voice in American fiction.', 'Stephen King', '978-0-385-08695-0', 1974, 0),
(0, 'Rage','Charlie Decker, a Maine high school senior, is called to a meeting with his principal about a previous incident in which he struck his chemistry teacher with a pipe wrench, leading to the teacher"s hospitalization and Charlie"s suspension. For unknown reasons, Charlie subjects the principal to a series of insulting remarks, resulting in his expulsion. Charlie storms out of the office and retrieves a pistol from his locker, then sets the contents of his locker on fire. He then returns to his classroom and fatally shoots his algebra teacher. The fire triggers an alarm, but Charlie forces his classmates to stay in the room, killing a janitor when he attempts to enter. As the other students and teachers evacuate the school, the police and media arrive at the scene', 'Stephen King', '	978-0-451-07645-8', 1977, 0),
(0, 'The Stand','The Stand is a post-apocalyptic horror/fantasy novel by American author Stephen King. It expands upon the scenario of his earlier short story "Night Surf" and outlines the total breakdown of society after the accidental release of a strain of influenza that had been modified for biological warfare causes an apocalyptic pandemic which kills off the majority of the world human population.', 'Stephen King', '978-0-385-12168-2', 1978, 0),
(0, 'The Long Walk','One hundred teenage boys participate in an annual walking contest called "The Long Walk" or just "The Walk". Each contestant, called a "Walker", must maintain a speed of at least four miles per hour; if he drops below that speed for 30 seconds, he receives a verbal warning. A Walker who slows down again after receiving three warnings is "ticketed". ', 'Stephen King', '978-0-451-08754-6', 1995, 0),
(0, 'The Dead Zone','The prologue introduces the two main characters. In 1953, a young boy named John Smith is knocked unconscious while ice-skating, When recovering, he mumbles a strange message to an adult on the scene. The knot on Johnny"s head fades after a few days, and he thinks no more of it. A few months later, the adult is seriously injured while he jump starts a car battery. Two years later, during an unconnected incident in Iowa, a young door to door Bible salesman, Greg Stillson, who suffers emotional issues and dreaming of greatness, vindictively kicks an aggressive dog to death.', 'Stephen King', '	978-0-670-26077-5', 1979, 0),
(0, 'Cujo','The story takes place in the setting of numerous King works: the fictional town of Castle Rock, Maine. Revolving around two local families, the narrative is interspersed with vignettes from the seemingly mundane lives of various other residents. There are no chapter headings but breaks in between passages to indicate when the narration switches to a different point of view.', 'Stephen King', '978-0-670-45193-7', 1981, 0),
(0, 'The Running Man ','In 2025, the world economy is in shambles and America has become a totalitarian dystopia. Ben Richards, an impoverished resident of the fictional Co-Op City, is unable to find work, having been blacklisted from his trade. ', 'Stephen King', '	978-0-451-11508-9', 1982, 0),
(0, 'The Dark Tower: The Gunslinger','As Roland travels across the desert in search of the man in black whom he knows as Walter, he encounters a farmer named Brown, and Zoltan, his black crow. Roland spends the night there, and recalls his time spent in Tull, a small town which Roland passed through not long before the start of the novel. The man in black had also stayed in the town; he brought a dead man back to life and left a trap for Roland. Roland meets the leader of the local church who reveals to him that the man in black has impregnated her with a demon. She turns the entire town against Roland; men, women, and children. Roland is forced to kill every resident of the town. When he awakens the next day, his mule is dead, forcing him to proceed on foot.', 'Stephen King', '978-0-937986-50-9', 1982, 0),
(0, 'Christine','Arnie brings Christine to a do-it-yourself auto-repair facility run by Will Darnell, who is suspected of using the garage as a front for illicit operations. As Arnie restores the automobile he becomes withdrawn, humorless, and cynical. However, he is also more confident and self-assured than usual. Dennis is puzzled by the changes in both his friend and Christine; the repair work proceeds haphazardly and the more extensive repairs, which Arnie can hardly afford, do not appear to be done by Arnie himself. Arnie"s appearance improves in tandem with Christine.', 'Stephen King', '	978-0-670-22026-7', 1983, 0),
(0, 'The Dark Tower II: The Drawing of the Three','Feverish and losing strength, Roland continues to trek north along the beach, where he eventually encounters three doors. Each door opens onto New York City at different periods in time (1987, 1964 and 1977, respectively) and, as Roland passes through these doors, he brings back the companions who will join him on his quest to the Dark Tower.', 'Stephen King', '	978-0-937986-90-5', 1987, 0),
(0, 'Misery','Paul Sheldon is the author of a best-selling series of Victorian-era romance novels surrounding the character Misery Chastain. He has just finished the manuscript of his new crime novel, Fast Cars, while staying at the Hotel Boulderado. Since 1974, he has completed the first draft of every one of his novels in the same hotel room in Colorado. With his latest project finished, he has an alcohol-induced impulse to drive to Los Angeles rather than fly back home to New York City. However, a snowstorm hits while he is driving through the mountains. Sheldon drives off a cliff and crashes upside down into a snowbank.1', 'Stephen King', '978-0-670-81364-3', 1987, 0),
(0, 'The Dark Tower III: The Waste Lands','The story begins five weeks after the end of The Drawing of the Three. Roland, Susannah, and Eddie have moved east from the shore of the Western Sea, and into the woods of Out-World. After an encounter with a gigantic cyborg bear named Shardik, they discover one of the six mystical Beams that hold the world together. The three gunslingers follow the Path of the Beam inland to Mid-World.', 'Stephen King', '978-0-937986-17-2', 1991, 0),
(0, 'Insomnia','The story is set in Stephen King"s multiverse in the fictional town of Derry, Maine. Ralph Roberts, who is retired, encounters his good-natured acquaintance Ed Deepneau at the local airfield, behaving aggressively and swearing obscenely at a driver he accuses of involvement in transporting fetal tissue from abortions. Some months later, and now a widower, Ralph encounters Ed"s wife Helen who has been badly beaten by her husband after having signed a pro-choice related petition.', 'Stephen King', '978-0-670-85503-2', 1994, 0),
(0, 'The Green Mile','A first-person narrative told by Paul Edgecombe, the novel switches between Paul as an old man in the Georgia Pines nursing home sharing his story with fellow resident Elaine Connelly in 1996, and his time in 1932 as the block supervisor of the Cold Mountain Penitentiary death row, nicknamed "The Green Mile" for the color of the floor"s linoleum. This year marks the arrival of John Coffey, a 6 ft 8 in powerfully built black man who has been convicted of raping and murdering two small white girls. During his time on the Mile, John interacts with fellow prisoners Eduard "Del" Delacroix, a Cajun arsonist, rapist, and murderer, and William Wharton ("Billy the Kid" to himself, "Wild Bill" to the guards), a wild-acting and dangerous multiple murderer who is determined to make as much trouble as he can before he is executed. Other inhabitants include Arlen Bitterbuck, a Native American convicted of killing a man in a fight over a pair of boots (also the first character to die in the electric chair); Arthur Flanders, a real estate executive who killed his father to perpetrate insurance fraud, and whose sentence is eventually commuted to life imprisonment (while serving his sentence, he is killed by another inmate in the laundry room); and Mr. Jingles, a mouse, to whom Del teaches various tricks.', 'Stephen King', '978-0451190567', 1996, 0),
(0, 'The Regulators','The story takes place in the fictional town of Wentworth, Ohio, a typical suburban community. On Poplar Street, an autistic boy named Seth has gained the power to control reality through the help of a being known as Tak. Soon, Poplar Street begins to change shape, transforming from a quiet suburb into a wild west caricature based on what Seth has seen on his television. Meanwhile, the other residents of the street are being attacked by the many beings that Seth"s imagination is creating, due to Tak"s control over them. These residents are forced to work together to stop Seth and Tak from completely transforming the world around them and stop Tak before he kills anyone else', 'Stephen King', '	978-0-525-94190-3', 1996, 0),
(0, 'The Dark Tower IV: Wizard and Glass','The novel begins where The Waste Lands ended. After Jake, Eddie, Susannah and Roland fruitlessly riddle Blaine the Mono for several hours, Eddie defeats the mad computer by telling childish jokes. Blaine is unable to handle Eddie"s "illogical" riddles and short-circuits.', 'Stephen King', '	978-1-880418-38-3', 1997, 0),
(0, 'Black House','A series of murders has begun to plague the town of French Landing, Wisconsin. The murderer is dubbed "The Fisherman", due to a conscious effort by the killer to emulate the methods of serial killer Albert Fish. Like Fish, French Landing"s killer targets children and indulges in cannibalism of the bodies. Two victims have already been discovered as the story opens, with a third awaiting discovery. The nature of the crimes, and the local police"s inability to capture the killer, have led people all over the region to become more anxious with each passing day, and certain elements of the local media exacerbate the situation with inflammatory and provocative coverage.', 'Stephen King', '978-0-375-50439-6', 2001, 0),
(0, 'The Dark Tower V: Wolves of the Calla','After escaping the alternate Topeka and the evil wizard Walter O"Dim and weathering the starkblast, Roland"s ka-tet begin to sense they are being followed in their travels. During this time, Eddie Dean and Jake Chambers are sent to New York, 1977, via a dream-state called todash. There they encounter Calvin Tower, a bookstore owner who gave Jake a book in The Waste Lands that proved integral to the quest for the Dark Tower. While in todash, Eddie and Jake discover that Tower owns the vacant lot that houses the rose that is the physical manifestation of the Dark Tower previously encountered by Jake in The Waste Lands. Jake and Eddie also discover that Enrico Balazar, the crime boss that appeared in The Drawing of the Three, is attempting to coerce Tower into selling the lot to the mysterious Sombra Corporation. If this happens, the rose (and the Dark Tower itself) will be destroyed.', 'Stephen King', '978-1-880418-56-7', 2003, 0),
(0, 'The Dark Tower VI: Song of Susannah','Taking place mainly in our world (New York City and East Stoneham, Maine), this book picks up where Wolves of the Calla left off, with the ka-tet employing the help of the Manni to open the magic door inside Doorway Cave. The ka-tet are split up by the magic door, or perhaps ka, and sent to different "wheres" and "whens" in order to accomplish several essential goals pertaining to their quest towards the mysterious Dark Tower', 'Stephen King', '978-1-880-41859-8', 2004, 0),
(0, 'The Dark Tower VII: The Dark Tower','Beginning where book six left off, Jake Chambers and Father Callahan battle the evil infestation within the Dixie Pig, a vampire lounge in New York City featuring roast human flesh and doors to other worlds. After fighting off and destroying numerous "Low-Men" and Type One Vampires, Callahan sacrifices himself to let Jake survive. In the other world - Fedic - Mia, her body now physically separated from Susannah Dean, gives birth to Mordred Deschain, the biological son of Roland Deschain and Susannah. The Crimson King is also a "co-father" of this prophetic child, so it is not surprising when "baby" Mordred''s first act is to shapeshift into a spider-creature and feast on his birth-mother. Susannah shoots but fails to kill Mordred, eliminates other agents of the Crimson King, and escapes to meet up with Jake at the cross-dimensional door beneath the Dixie Pig which connects to Fedic. Maturing at an accelerated rate, Mordred later stalks Roland and the other gunslingers throughout this adventure, shifting from human to spider as the need arises, seething with an instinctive rage toward Roland, his "white daddy."', 'Stephen King', '978-1-880418-62-8', 2004, 0),
(0, 'Duma Key','Edgar Freemantle, a contractor in St. Paul, Minnesota, barely survives a horrific on-site accident where his truck is crushed by a crane. Freemantle"s right arm is amputated, and severe injuries to his head cause Edgar to have problems with speech, vision, and memory. As a result, Edgar also has violent mood swings and thoughts of suicide. During one of those mood swings, he attacks his wife, who later cites that as a main reason why she divorced him.', 'Stephen King', '978-1-4165-5251-2', 2008, 0),
(0, 'The Dark Tower: The Wind Through the Keyhole','The novel begins with Roland and his ka-tet arriving at a river on their journey to the Dark Tower. An elderly man who operates a ferry gets them across the river, and warns them that a severe depression (starkblast) is coming, and that they can find shelter in a building a few miles ahead. They reach the shelter just in time, and while they wait out the storm, Roland tells them of an adventure in his youth to keep them occupied: "The Skin-Man."', 'Stephen King', '	1-880418-76-2', 2012, 0),
(0, 'Joyland','The novel is set at a North Carolina amusement park in 1973 and involves a carny who must confront the "legacy of a vicious murder and the fate of a dying child". Devin Jones, who takes a summer job at Joyland in North Carolina, is a student at the University of New Hampshire. Devin is told, during his interview by the resident fortune teller, that he will meet two children that summer. One is a girl with a red hat. The other is a boy with a dog. One of them has The Sight. After securing lodging for the summer at a rooming house and making friends with some of the other summer help, Jones finds that he has a talent for "wearing the fur," Joyland-talk for portraying Howie the Happy Hound, Joyland"s mascot. He also works with and befriends one of the other longtime park employees - Lane Hardy. One day, he saves the aforementioned young girl in a red hat from choking on a park hot dog. The heroics earn him the trust and admiration of the park"s owner.', 'Stephen King', '	978-1-78116-264-4', 2013, 0),
(0, 'Doctor Sleep ','Following the events of The Shining, after receiving a settlement from the owners of the Overlook Hotel, Danny Torrance remains psychologically traumatized as his mother Wendy slowly recovers from her injuries. Angry ghosts from the Overlook, including the woman from Room 217, still want to find Danny and eventually consume his phenomenal "shining" power. Dick Hallorann, the Overlook"s chef, teaches Danny to create lockboxes in his mind to contain the ghosts, including that of former Overlook owner Horace Derwent.', 'Stephen King', '	978-1-4767-2765-3', 2013, 0),
(0, 'Sleeping Beauties ','In the impoverished town of Dooling, part of the fictional Tri-Counties region of Appalachia, a bizarre murder occurs when two men running a meth lab out of their trailer are beaten to death by a mysterious woman, who then sets fire to the lab before allowing herself to be arrested by the local sheriff, Lila Norcross. At the same time, reports start coming in of a mysterious sickness spreading across the world, which causes women to fall into a deep sleep, cocooned in a strange material. Dubbed "Aurora", the disease also causes the sleeping women to enter into a homicidal rage, attacking and brutally murdering anyone who tries to open the cocoons.', 'Stephen King', '978-1-5011-6340-1', 2017, 0);
